import { Router } from 'express';
import rateLimit from 'express-rate-limit';
import { authenticate } from '../middleware/authenticate.js';
import { permit } from '../middleware/authorize.js';
import * as auth from '../modules/auth/controllers/authController.js';
import * as warehouse from '../modules/warehouses/controllers/warehouseController.js';
import * as user from '../modules/users/controllers/userController.js';
import * as product from '../modules/products/controllers/productController.js';
import * as subProduct from '../modules/sub-products/controllers/subProductController.js';
import * as consumable from '../modules/consumables/controllers/consumableController.js';
import * as sale from '../modules/sales/controllers/salesController.js';
import * as ledger from '../modules/inventory/controllers/stockTransactionController.js';
import * as setting from '../modules/settings/controllers/settingsController.js';

const router = Router();
const loginLimiter = rateLimit({ windowMs: 15 * 60 * 1000, limit: 10, skipSuccessfulRequests: true, standardHeaders: true, legacyHeaders: false, message: { message: 'Too many login attempts. Please wait a few minutes and try again.' } });
router.get('/health', (_req, res) => res.json({ status: 'ok' }));
router.post('/auth/login', loginLimiter, auth.login);
router.get('/auth/me', authenticate, auth.me);
router.use(authenticate);
router.get('/warehouses', warehouse.list);
router.post('/warehouses', permit('warehouse:manage'), warehouse.create);
router.patch('/warehouses/:id', permit('warehouse:manage'), warehouse.update);
router.delete('/warehouses/:id', permit('warehouse:manage'), warehouse.remove);
router.get('/users', permit('user:manage'), user.list);
router.post('/users', permit('user:manage'), user.create);
router.patch('/users/:id', permit('user:manage'), user.update);
router.delete('/users/:id', permit('user:manage'), user.remove);
router.get('/products', product.list);
router.post('/products', permit('product:manage'), product.create);
router.patch('/products/:id', permit('product:manage'), product.update);
router.post('/products/:id/stock', permit('stock:manage'), product.adjustStock);
router.delete('/products/:id', permit('product:manage'), product.remove);
router.get('/sub-products', permit('product:manage'), subProduct.list);
router.post('/sub-products', permit('product:manage'), subProduct.create);
router.patch('/sub-products/:id', permit('product:manage'), subProduct.update);
router.delete('/sub-products/:id', permit('product:manage'), subProduct.remove);
router.get('/consumables', permit('product:manage'), consumable.list);
router.post('/consumables', permit('product:manage'), consumable.create);
router.patch('/consumables/:id', permit('product:manage'), consumable.update);
router.delete('/consumables/:id', permit('product:manage'), consumable.remove);
router.get('/stock-transactions', permit('inventory:view'), ledger.list);
router.get('/sales-requests', permit('sales:view'), sale.list);
router.post('/sales-requests', permit('sales:create'), sale.create);
router.post('/sales-requests/:id/approve', permit('sales:process'), sale.approve);
router.post('/sales-requests/:id/cancel', permit('sales:process'), sale.cancel);
router.get('/settings', setting.get);
router.put('/settings', permit('settings:manage'), setting.save);
export default router;
